# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ysalaun <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/24 11:32:30 by ysalaun           #+#    #+#              #
#    Updated: 2017/07/24 11:55:51 by ysalaun          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
FLAGS = -Wall -Werror -Wextra -o
SRC = doop.c calcul.c print.c

all:
	gcc $(FLAGS) $(NAME) $(SRC)
clean:
	/bin/rm -f "do-op"
